#pythagoras vragen


PYTHAGORAS_VRAGEN = [
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 3 en 4 zijn?", "antwoord": 5},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 5 en 12 zijn?", "antwoord": 13},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 8 en 15 zijn?", "antwoord": 17},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 6 en 8 zijn?", "antwoord": 10},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 40 zijn?", "antwoord": 41},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 7 en 24 zijn?", "antwoord": 25},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 12 en 16 zijn?", "antwoord": 20},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 15 en 20 zijn?", "antwoord": 25},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 12 zijn?", "antwoord": 15},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 8 en 6 zijn?", "antwoord": 10},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 10 en 24 zijn?", "antwoord": 26},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 20 en 21 zijn?", "antwoord": 29},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 11 en 60 zijn?", "antwoord": 61},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 16 en 63 zijn?", "antwoord": 65},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 33 en 56 zijn?", "antwoord": 65},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 36 en 77 zijn?", "antwoord": 85},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 48 en 55 zijn?", "antwoord": 73},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 60 en 91 zijn?", "antwoord": 109},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 28 en 45 zijn?", "antwoord": 53},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 5 en 5 zijn?", "antwoord": 7.07},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 7 en 7 zijn?", "antwoord": 9.9},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 9 zijn?", "antwoord": 12.7},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 10 en 10 zijn?", "antwoord": 14.1},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 12 en 5 zijn?", "antwoord": 13},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 4 en 10 zijn?", "antwoord": 10.8},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 6 en 11 zijn?", "antwoord": 12.5},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 13 en 14 zijn?", "antwoord": 19.1},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 16 zijn?", "antwoord": 18.4},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 14 en 48 zijn?", "antwoord": 50},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 8 en 17 zijn?", "antwoord": 18.8},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 24 en 45 zijn?", "antwoord": 51},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 27 en 36 zijn?", "antwoord": 45},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 15 en 36 zijn?", "antwoord": 39},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 40 en 75 zijn?", "antwoord": 85},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 32 en 60 zijn?", "antwoord": 68},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 12 zijn?", "antwoord": 15},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 18 en 24 zijn?", "antwoord": 30},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 25 en 60 zijn?", "antwoord": 65},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 45 en 28 zijn?", "antwoord": 53},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 33 en 56 zijn?", "antwoord": 65},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 12 en 9 zijn?", "antwoord": 15},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 7 en 24 zijn?", "antwoord": 25},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 8 en 15 zijn?", "antwoord": 17},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 40 zijn?", "antwoord": 41},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 20 en 21 zijn?", "antwoord": 29},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 12 en 16 zijn?", "antwoord": 20},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 30 en 40 zijn?", "antwoord": 50},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 36 en 77 zijn?", "antwoord": 85},
    {"vraag": "Wat is de schuine zijde als de rechthoekszijden 9 en 12 zijn?", "antwoord": 15},
]
